In [1]:
## load packages 
import pandas as pd
import re
import numpy as np

## nltk imports
import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# uncomment and download if this is your first 
# time running 
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')

## sentiment analysis
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

## specify to print all output in a call
## and not just first
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/streetroberts/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/streetroberts/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [2]:
## spacy --- if you get an error at the load step
## need to download en_core_web_sm (google)
import spacy
sp = spacy.load('en_core_web_sm')
import en_core_web_sm
nlp = en_core_web_sm.load()

In [6]:
tweets = pd.read_pickle("data/Raw_Tweets.pkl")

In [7]:
tweets.head()
tweets.info

# valuable variables: text, date, (is there a number of retweets? or likes?")
# should we filter for "en"?

,tweetid,userid,date,lang,text,tweet_type,friends_count,followers_count,statuses_count,mentionid,rt_userid,rt_tweetid,qtd_userid,qtd_text,qtd_tweetid
12221,1221208309728006145,418859255,Sat Jan 25 23:08:44 +0000 2020,en,"RT @DepSecHargan: Every year in the US, 34,800...",retweeted_tweet_without_comment,638,1837,17778,[920035992073064450],9.200360e+17,1.221208e+18,NaN,NaN,NaN
28315,1221213073652043776,14499829,Sat Jan 25 23:27:40 +0000 2020,en,WHO’s risk assessment of the new #coronavirus ...,original,1743,5196950,46697,[],NaN,NaN,NaN,NaN,NaN
6092,1222281847163576321,1135486501,Tue Jan 28 22:14:35 +0000 2020,en,#FYI: 50 million are under travel restrictions...,original,950,27025,11145,[9624742],NaN,NaN,NaN,NaN,NaN
13618,1222289121118511104,117793973,Tue Jan 28 22:43:30 +0000 2020,en,What should I do if I have traveled to China a...,original,1236,5860,4578,[],NaN,NaN,NaN,NaN,NaN
19205,1222285279047843843,1465196934,Tue Jan 28 22:28:14 +0000 2020,en,Disease outbreaks can result in misinformation...,original,1946,3581,4636,[],NaN,NaN,NaN,NaN,NaN

<bound method DataFrame.info of                     tweetid      userid                            date lang  \
12221   1221208309728006145   418859255  Sat Jan 25 23:08:44 +0000 2020   en
28315   1221213073652043776    14499829  Sat Jan 25 23:27:40 +0000 2020   en
6092    1222281847163576321  1135486501  Tue Jan 28 22:14:35 +0000 2020   en
13618   1222289121118511104   117793973  Tue Jan 28 22:43:30 +0000 2020   en
19205   1222285279047843843  1465196934  Tue Jan 28 22:28:14 +0000 2020   en
...                     ...         ...                             ...  ...
116861  1320011868228997124    29201047  Sat Oct 24 14:38:48 +0000 2020   en
118583  1320012011967815680  2353731720  Sat Oct 24 14:39:22 +0000 2020   en
159427  1320015434972909568    18909919  Sat Oct 24 14:52:59 +0000 2020   en
159487  1320015440249225218    44783853  Sat Oct 24 14:53:00 +0000 2020   en
166622  1320016039103598592  3218464527  Sat Oct 24 14:55:23 +0000 2020   en

                                                     text  \
12221   RT @DepSecHargan: Every year in the US, 34,800...
28315   WHO’s risk assessment of the new #coronavirus ...
6092    #FYI: 50 million are under travel restrictions...
13618   What should I do if I have traveled to China a...
19205   Disease outbreaks can result in misinformation...
...                                                   ...
116861  We’re moving in the wrong direction &amp; ther...
118583  .@WV_DHHR reports as of 10:00 a.m., October 24...
159427  We must tackle this pandemic together. We can ...
159487  RT @CDCgov: Today is a good day to talk with y...
166622  RT @PennsylvaniaGov: Today is Drug #TakeBackDa...

                             tweet_type  friends_count  followers_count  \
12221   retweeted_tweet_without_comment            638             1837
28315                          original           1743          5196950
6092                           original            950            27025
13618                          original           1236             5860
19205                          original           1946             3581
...                                 ...            ...              ...
116861                         original           1009           488682
118583                         original            307             5898
159427                         original           4595            27281
159487  retweeted_tweet_without_comment            396          1013652
166622  retweeted_tweet_without_comment            953            65927

        statuses_count             mentionid     rt_userid    rt_tweetid  \
12221            17778  [920035992073064450]  9.200360e+17  1.221208e+18
28315            46697                    []           NaN           NaN
6092             11145             [9624742]           NaN           NaN
13618             4578                    []           NaN           NaN
19205             4636                    []           NaN           NaN
...                ...                   ...           ...           ...
116861           12147                    []           NaN           NaN
118583            8093          [2353731720]           NaN           NaN
159427           12771                    []           NaN           NaN
159487           22511           [146569971]  1.465700e+08  1.318949e+18
166622           14938          [3762413663]  3.762414e+09  1.319987e+18

        qtd_userid qtd_text  qtd_tweetid
12221          NaN      NaN          NaN
28315          NaN      NaN          NaN
6092           NaN      NaN          NaN
13618          NaN      NaN          NaN
19205          NaN      NaN          NaN
...            ...      ...          ...
116861         NaN      NaN          NaN
118583         NaN      NaN          NaN
159427         NaN      NaN          NaN
159487         NaN      NaN          NaN
166622         NaN      NaN          NaN

[59887 rows x 15 columns]>